version: '3'
services: 
  api:
    restart: always
    build: ./new-code-api
    volumes: 
      - ./new-code-api/:/var/www/
    depends_on: 
      - db

  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: code
    volumes: 
      - "./.docker/dbdata:/var/lib/postgresql/data"

  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8001:80"
    volumes: 
      - ./new-code-api/:/var/www
    depends_on:
        - api

  my-app:
    build: ./new-code-app
    restart: always
    ports:
      - 8081:8080
    volumes:
      - './new-code-app/:/app'
      - '/app/node_modules'